// <auto-generated />
using System;
using Hive.Server.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hive.Server.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211123193617_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Hive.Shared.WeatherForecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Forecasts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d4d73f1-71ab-42a7-bb58-769e7b332595"),
                            Date = new DateTime(2021, 11, 25, 1, 6, 16, 947, DateTimeKind.Local).AddTicks(9877),
                            Summary = "Scorching",
                            TemperatureC = 29
                        },
                        new
                        {
                            Id = new Guid("ac5677a9-ac8e-48dc-ab8c-06985b8b0458"),
                            Date = new DateTime(2021, 11, 26, 1, 6, 16, 949, DateTimeKind.Local).AddTicks(2818),
                            Summary = "Balmy",
                            TemperatureC = 10
                        },
                        new
                        {
                            Id = new Guid("122ba593-dd82-4061-b664-1f40c91dd856"),
                            Date = new DateTime(2021, 11, 27, 1, 6, 16, 949, DateTimeKind.Local).AddTicks(2868),
                            Summary = "Bracing",
                            TemperatureC = 38
                        },
                        new
                        {
                            Id = new Guid("7c0766fa-3223-40a9-b7f0-ef4cabb9b9d3"),
                            Date = new DateTime(2021, 11, 28, 1, 6, 16, 949, DateTimeKind.Local).AddTicks(2872),
                            Summary = "Bracing",
                            TemperatureC = 37
                        },
                        new
                        {
                            Id = new Guid("86b1ced5-8506-4f71-8c2d-297faddb62f4"),
                            Date = new DateTime(2021, 11, 29, 1, 6, 16, 949, DateTimeKind.Local).AddTicks(2876),
                            Summary = "Mild",
                            TemperatureC = -11
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
